[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "fund-mithril-lib-xml"
version = "0.4.0"
requires-python = ">=3.11"
dependencies = ["fund-mithril-lib-interop @ git+https://github.com/mithril-lang/fund.mithril.lib.interop.git@c622e7ad4ca862416c80c11508ccdb636abd3835", "lxml==6.1.3", "xmlschema==4.3.2"]

[project.entry-points."mithril.interop.plugins"]
"fund.mithril.lib.xml" = "mithril_xml.plugin:Plugin"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.xml", "*.cljk", "*.kotoba", "*.mith"]
