[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "fund-mithril-xml"
version = "0.2.0"
requires-python = ">=3.11"
dependencies = ["fund-mithril-interop @ git+https://github.com/mithril-lang/fund.mithril.interop.git@dee5c5a85e62e1383dac85a65960049385af8532", "lxml==6.1.3", "xmlschema==4.3.2"]

[project.entry-points."mithril.interop.plugins"]
"fund.mithril.xml" = "mithril_xml.plugin:Plugin"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.xml"]
